name: Build Executables

on:
  push:
    tags:
      - v*  # Matches tags starting with 'v'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    env:
      MAIN_PY_FILE: 'bouncer.py'  # Define the path to your main.py file here

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile ${{ env.MAIN_PY_FILE }}

    - name: Upload Artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: bouncer-windows
        path: dist/

    - name: Upload Artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: bouncer-linux
        path: dist/

    - name: Upload Artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: bouncer-macos
        path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4 # We are downloading all of the artifacts to the root of the runtime directory
    
    - name: List files in runtime folder
      run: ls -R 
    
    - name: Compress Windows Executables
      run: zip -r bouncer-windows.zip bouncer-windows/

    - name: Compress Linux Executables
      run: zip -r bouncer-linux.zip bouncer-linux/

    - name: Compress macOS Executables
      run: zip -r bouncer-macos.zip bouncer-macos/

    - name: List files in runtime folder
      run: ls -R 
      
    - name: Create Release and Upload Artifacts
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        body: |
          This release contains executables for all platforms.
        draft: false
        prerelease: false
        generateReleaseNotes: true
        allowUpdates: true
        artifacts: "bouncer-macos.zip, bouncer-linux.zip, bouncer-windows.zip "
