name: Build Executables

on:
  push:
    tags:
      - v*  # Matches tags starting with 'v'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    env:
      MAIN_PY_FILE: 'bouncer.py'  # Define the path to your main.py file here

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile ${{ env.MAIN_PY_FILE }}

    - name: Upload Artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-executables
        path: dist/

    - name: Upload Artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-executables
        path: dist/

    - name: Upload Artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: macos-executables
        path: dist/

  prep_release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows Artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-executables
        path: ./dist/windows-executables

    - name: Download Linux Artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-executables
        path: ./dist/linux-executables

    - name: Download macOS Artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-executables
        path: ./dist/macos-executables

    - name: Compress Windows Executables
      run: zip -r windows-executables.zip ./dist/windows-executables/

    - name: Compress Linux Executables
      run: zip -r linux-executables.zip ./dist/linux-executables/

    - name: Compress macOS Executables
      run: zip -r macos-executables.zip ./dist/macos-executables/

  release:
    needs: prep_release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Release and Upload Artifacts
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          This release contains executables for all platforms.
        draft: false
        prerelease: false
        artifacts: |
          ./dist/windows-executables.zip
          ./dist/linux-executables.zip
          ./dist/macos-executables.zip
